
language: 'node_js'

cache: 'yarn'

node_js:
  - '9'
  - '8'

before_install:
  - 'export YARN_IGNORE_ENGINES=true'

install:
  - 'yarn install'

script:
  - 'yarn run lint'
  - 'yarn run test'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

notifications:
  email: false
